services:
  - type: web
    name: artist-blend-backend
    env: go
    plan: free
    buildCommand: cd backend && go build -o main .
    startCommand: cd backend && ./main
    envVars:
      - key: GIN_MODE
        value: release
      - key: SPOTIFY_CLIENT_ID
        sync: false
      - key: SPOTIFY_CLIENT_SECRET
        sync: false
      - key: SPOTIFY_REDIRECT_URI
        sync: false
      - key: FRONTEND_URL
        sync: false
      - key: MONGO_URI
        sync: false

  - type: web
    name: artist-blend-frontend
    env: static
    plan: free
    buildCommand: cd frontend && npm install && npm run build
    staticPublishPath: frontend/dist
    routes:
      - type: rewrite
        source: "/*"
        destination: "/index.html"
    envVars:
      - key: VITE_API_URL
        sync: false
